name: Vixio
description: Vixio, The Discord addon created to meet all of your Discord needs.
main: me.iblitzkriegi.vixio.Vixio
version: ${project.version}
author: iBlitzkriegi, sky_high (Pikachu)
website: http://vixio.space
depend: [Skript]
commands:
  vixio:
    description: Default command for Vixio
    usage: /<command>
